# Generated by Django 2.0 on 2020-08-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USER_NAME', models.CharField(default='NULL', max_length=250, unique=True)),
                ('PASSWORD', models.CharField(default='KIET123', max_length=250)),
                ('father_name', models.CharField(default='father', max_length=250)),
                ('email', models.CharField(default='kiet123@.com', max_length=250, unique=True)),
                ('branch', models.CharField(default='IT', max_length=250)),
                ('phone_no', models.BigIntegerField(default='1234567890', unique=True)),
                ('STATUS', models.CharField(default='NO QUERY', max_length=100)),
                ('ACTIVE_STATUS', models.CharField(default='ACTIVE', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
